# Generated by Django 2.2.13 on 2021-04-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_auto_20190706_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='types',
            field=models.CharField(choices=[('intro', 'Intro'), ('inception', 'Project inception'), ('middle', 'Middle of project'), ('end', 'End of project'), ('prep', 'Interview preparation and career advice'), ('postponed', 'Postponed (Valid Reason)'), ('other', 'Other'), ('no-show', '**No-show**')], max_length=255),
        ),
    ]
