# Generated by Django 2.2.13 on 2021-04-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='project',
            field=models.CharField(choices=[('intro', 'Intro/Interview'), ('userCentric', 'User Centric Front End Development (MS1)'), ('interactive', 'Interactive Front End Development (MS2)'), ('dataCentric', 'Data Centric Development (MS3)'), ('fullStack', 'Full Stack Frameworks with Django (MS4)'), ('pp1', 'HTML/CSS Essentials (PP1)'), ('pp2', 'JavaScript Essentials (PP2)'), ('pp3', 'Python Essentials (PP3)'), ('pp4', 'Full Stack Toolkit (PP4)'), ('eCommerce', 'eCommerce (PP5)')], max_length=255),
        ),
    ]
